### ISSUE TITLE
[Bug]: no constuctor?

### ISSUE THREAD

**Issue by dgudim** [DKRCommands/DKRCommands#1]
### ⚠️ Please verify that this bug has NOT been raised before.

- [x] I checked and didn't find similar issue

### ✏ Description

basically can't initialize DKRCommands, it says 

```ruby
This expression is not constructable.
  Type 'typeof import(".../node_modules/dkrcommands/dist/index")' has no construct signatures.
```
my import is as follows: 
```js
import DKRCommands from "dkrcommands"
```

### 👟 Reproduction steps

just ```npm install dkrcommands``` and paste basic example from documentation

### 🔢 DKRCommands version

1.0.0-beta.1

### 💻 Operating system

Linux

### 🔢 Node.js version

18.9.0

### 👀 Expected behavior

works

### 😥 Actual behavior

doesn't work

**Comment by karelkryda** [comment]
Hello,
I haven't tested all parts of the documentation yet, and I apologize for this error.
Correctly you should use:
```ts
import { DKRCommands } from "dkrcommands";
```
I will fix this in the documentation immediately.

Thank you for reporting this bug

**Comment by dgudim** [comment]
Thanks, but i think i just copied it wrongly somehow or replaced the wokcommands import 
```js 
import WOKCommands from 'wokcommands'
```
with 
```js 
import DKRCommands from 'dkrcommands'
```
without a second thought
anyway, it works now, closing the issue
