### ISSUE TITLE
Question regarding Command Options Choices

### ISSUE THREAD

**Issue by DJ45X** [DKRCommands/DKRCommands#4]
Hello! Hope you are well!

I did not see any mention in the [documentation ](https://karel-kryda.gitbook.io/dkrcommands/commands/command-properties) in regards to [Command Option Choices](https://discordjs.guide/slash-commands/advanced-creation.html#choices). I need to build a slash command that has choosable options for my users.

example: `/stream-request [time] [day]`
**Time** = `[6pm, 7pm, 8pm, 9pm, 10pm]`.
**Day** = `[Saturday, Sunday]`

I know the `.addChoices` from the discord.js documentation, but that's if I was using SlashCommandBuilder. How do you have this implemented in DKRCommands?

This command/ event handler has been a huge life saver! Hope you have been well and look forward to your reply!

**-DJ45X**

**Comment by DJ45X** [comment]
After some searching, I did finally figure it out. Was able to reference [this](https://discord.com/developers/docs/interactions/application-commands#making-a-global-command). 

If possible, perhaps it would be a little helpful for others that you include an example in your [docs](https://karel-kryda.gitbook.io/dkrcommands/commands/command-properties).

My usage [here](https://srcshare.io/63ed477f5051f49b7d65939d).

Have a great day!

**Comment by karelkryda** [comment]
Hello,
information about slash command parameters is available [here](https://karel-kryda.gitbook.io/dkrcommands/commands/slash-commands#slash-command-arguments-options). I have extended the documentation to show the `choices` property.

I hope it's ok now and DKRCommands will help you in the development of your bot. If you have any problem, feel free to contact me again.

Karel 🙂

**Comment by DJ45X** [comment]
> Hello, information about slash command parameters is available [here](https://karel-kryda.gitbook.io/dkrcommands/commands/slash-commands#slash-command-arguments-options). I have extended the documentation to show the `choices` property.
> 
> I hope it's ok now and DKRCommands will help you in the development of your bot. If you have any problem, feel free to contact me again.
> 
> Karel 🙂

It has been an absolute dream to use! I've been getting so much praise from my users and it wouldn't be possible without your command handler (and by extension, WOKC).
